# 
# import and create a copy of the environment so we don't screw up anyone elses env.
#
Import('irdb_env')
myenv=irdb_env.Clone()

#
# set the files to build and the output file name
#
files=Glob( Dir('.').srcnode().abspath+"/*.cpp")
pgm="libmsan.so"


#
# override the default libs as we need more libraries for this transform
# 
libs=Split("irdb-core irdb-transform irdb-deep irdb-util irdb-elfdep capstone") 

#
# build and install the transform, by default
# 
pgm=myenv.SharedLibrary(pgm,  files,  LIBS=libs)
install=myenv.Install("$INSTALL_PATH/", pgm)
Default(install)


#
# and we're done
#
Return('install')
